name: "_INTERNAL_Global Release"

on:
  workflow_call:

jobs:
  release:
    name: "Semantic Release"
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm build:lib
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"