name: "[DEVELOP] Workflow"

on:
  push:
    branches:
      - develop

jobs:
  commitlint:
    name: "[${{ github.ref_name }}] Conventional Commits"
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/.reusable.commits.yml