name: "Release Workflow"

on:
  push:
    branches:
      - main
      - develop

jobs:
  commitlint:
    name: "[${{ github.ref_name }}] Conventional Commits"
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/.reusable.commits.yml

  tests:
    name: "[${{ github.ref_name }}] Tests"
    permissions:
      contents: read
    uses: ./.github/workflows/.reusable.tests.yml

  release:
    name: "[${{ github.ref_name }}] Release"
    needs: [commitlint, tests]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/.reusable.release.yml